<!-- templates/components/header.phtml -->

<!DOCTYPE html>
<html lang="ru">

    <head>
        <title>Slim Project</title>
    </head>

    <body>

        <header>
            <!--Buttons-->
            <a href="/users">
                <button>
                    Users
                </button>
            </a>
            <?php if (isset($_SESSION['name'])) :?>
                <a href="/users/<?= $_SESSION['id'] ?>">
                    <button>
                        Me
                    </button>
                </a>
            <?php else :?>
                <a href="/login">
                    <button>
                        Login
                    </button>
                </a>
                <a href="/users/new">
                    <button>
                        Create new user
                    </button>
                </a>
            <?php endif; ?>

        </header>