<!-- templates/users/edit.phtml -->

<?php require 'templates/components/header.phtml'; ?>

<main>
    <!--Edit user-->
    <form action="/users/<?= $user['id'] ?>" method="post">
        <input type="hidden" name="_METHOD" value="PATCH">
        <div>
            <h1>Edit personal data <?= $user['name'] ?></h1>
            <b>ID</b> = <?= $user['id'] ?>
        </div>
        <br>
        <div>
            <label>
                <b>Username</b>
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>" >
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['name'])): ?>
                <div style="color: red"><?= $errors['name'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <div>
            <label>
                <b>Email</b>
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>" >
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['email'])): ?>
                <div style="color: red"><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <input type="submit" value="Update" style="color: green">
    </form>
    <br>
    <form action="/users/<?= $user['id'] ?>" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Remove" style="color: gray">
    </form>

</main>
<br>
<?php require 'templates/components/footer.phtml'; ?>