<!-- templates/users/index.phtml -->

<!DOCTYPE html>
<html lang="ru">

<head>
    <title>Users</title>
</head>

<a href="/users/new">
    <button>
        Create new user
    </button>
</a>

<body>
    <h1>Users</h1>
    <!--Displays a message that the user was added successfully-->
    <?php if (count($flash) > 0) : ?>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <i style="color: green"><?= $message ?></i>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
    <br>
    <form action="/users">
        <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" placeholder="Name">
        <input type="submit" value="Search">
    </form>
    <hr>
    <!--Displays all usernames-->
    <?php foreach ($users as $user): ?>
    <li><b><i><?= htmlspecialchars($user) ?></i></b></li>
    <?php endforeach ?>
</body>

</html>