<head>
    <title>Users</title>
</head>
<body>
    <h1>Users</h1>
    <?php if (count($flash) > 0) : ?>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <i style="color: green"><?= $message ?></i>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
    <br>
    <form action="/users">
        <input type="search" name="term" value="<?= htmlspecialchars($term) ?>">
        <input type="submit" value="Search">
    </form>
    <hr>
    <?php foreach ($users as $user): ?>
    <li><b><i><?= htmlspecialchars($user) ?></i></b></li>
    <?php endforeach ?>
</body>