<head>
    <title>Users</title>
</head>
<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>
<body>
    <form action="/users">
        <input type="search" name="term" value="<?= htmlspecialchars($term) ?>">
        <input type="submit" value="Search">
    </form>
    <hr>
    <?php foreach ($users as $user): ?>
    <li><b><i><?= htmlspecialchars($user) ?></i></b></li>
    <?php endforeach ?>
</body>