<!-- templates/users/new.phtml -->

<!DOCTYPE html>
<html lang="ru">

<head>
    <title>New User</title>
</head>

<a href="/users">
    <button>
        Users
    </button>
</a>

<body>
    <form action="/users" method="post">
        <h1>New User</h1>
        <hr>
        <br>
        <div>
            <label>
                <b>Nickname *</b>
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>">
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['name'])): ?>
                <div><?= $errors['name'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <div>
            <label>
                <b>Email *</b>
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['email'])): ?>
                <div><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <input type="submit" value="Submit">
    </form>
</body>

</html>