<head>
    <title>New User</title>
</head>
<body>
    <form action="/users/new" method="post">
        <h1>New User</h1>
        <hr>
        <br>
        <div>
            <label>
                <b>Nickname</b>
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
            </label>
        </div>
        <br>
        <div>
            <label>
                <b>Email</b>
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
            </label>
        </div>
        <br>
        <input type="submit" value="Submit">
    </form>
</body>