<!-- templates/users/new.phtml -->

<!DOCTYPE html>
<html lang="ru">

<head>
    <title>Sign in</title>
</head>

<body>
    <h1>Hexlet Slim Project</h1>

    <!--Buttons-->
    <a href="/">
        <button>
            About
        </button>
    </a>
    <a href="/users">
        <button>
            Users
        </button>
    </a>
    <a href="/users/new">
        <button>
            Sign in
        </button>
    </a>

    <!--Sign in-->
    <form action="/users" method="post">
        <h1>Sign in</h1>
        <div>
            <label>
                <b>Username *</b>
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>">
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['name'])): ?>
                <div><?= $errors['name'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <div>
            <label>
                <b>Email *</b>
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
            </label>
            <!--Displays a message that the field cannot be empty-->
            <?php if (isset($errors['email'])): ?>
                <div><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
        <br>
        <input type="submit" value="Submit">
    </form>
</body>

</html>