<!-- templates/users/show.phtml -->

<?php require 'templates/components/header.phtml'; ?>

<main>
    <h1>Personal data <?= $user['name'] ?></h1>
    <!--Displays a message that the user was updated successfully-->
    <?php if (count($flash) > 0) : ?>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <i style="color: green"><?= $message ?></i>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
    <p>
        <!--Personal data-->
        <b>ID</b> = <?= $user['id'] ?><br>
        <b>Username</b> = <?= $user['name'] ?><br>
        <b>Email</b> = <?= $user['email'] ?>
    </p>
    <?php if ($_SESSION['id'] === $user['id']) :?>
        <a href="/users/<?= $user['id'] ?>/edit">
            <input type="submit" value="Profile update">
        </a>
        <form action="/login" method="post">
            <input type="hidden" name="_METHOD" value="DELETE">
            <br>
            <input type="submit" value="Unlogin" style="color: gray">
        </form>
    <?php endif; ?>
</main>
<br>
<?php require 'templates/components/footer.phtml'; ?>