<!-- templates/users/show.phtml -->

<!DOCTYPE html>
<html lang="ru">

<head>
    <title>Personal data</title>
</head>

<body>
    <h1>Hexlet Slim Project</h1>

    <!--Buttons-->
    <a href="/">
        <button>
            About
        </button>
    </a>
    <a href="/users">
        <button>
            Users
        </button>
    </a>
    <a href="/users/new">
        <button>
            Sign in
        </button>
    </a>
    
    <!--Personal data-->
    <h1>Personal data</h1>
    <p>
        <b>ID</b> = <?= htmlspecialchars($id) ?><br>
        <b>Username</b> = <?= htmlspecialchars($username) ?><br>
        <b>Email</b> = <?= htmlspecialchars($email) ?>
    </p>
    <input type="submit" value="Update">
</body>

</html>