<!-- templates/users/users.phtml -->

<?php require 'templates/components/header.phtml'; ?>

<main>
    <!--Users-->
    <h1>Users</h1>
    <!--Displays a message that the user was added successfully-->
    <?php if (count($flash) > 0) : ?>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <i style="color: green"><?= $message ?></i>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
    <form action="/users">
        <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" placeholder="Name">
        <input type="submit" value="Search">
    </form>
    <br>
    <!--Displays all usernames-->
    <?php if (isset($users)) : ?>
        <?php foreach ($users as $user): ?>
        <div>
            <a href="/users/<?= $user['id'] ?>">
                <li><b><i><?= $user['name'] ?></i></b></li>
            </a>
        </div>
        <?php endforeach ?>
    <?php else :?>
        <div>
            <i>Nothing to display :c</i>
        </div>
    <?php endif; ?>

</main>
<br>
<?php require 'templates/components/footer.phtml'; ?>